stages:
  - Build
  - Docker

before_script:
  - export GOPATH=${CI_PROJECT_DIR}/.cache

Run build:
  image: golang:1.17
  stage: Build
  script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build
  artifacts:
    expire_in: 2 h
    paths:
      - .bin

Build Image:
  image: docker:20.10.1
  stage: Docker
  services:
    - docker:20.10.1-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - branches